"""profile picture path field in user model

Revision ID: 601609624f8f
Revises: 241bcd1fe118
Create Date: 2023-07-10 13:52:29.454109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601609624f8f'
down_revision = '241bcd1fe118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
