"""removed profile_picture attribute

Revision ID: 7a2bc20aa6b2
Revises: 2646af2341c4
Create Date: 2023-07-12 12:29:02.724933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2bc20aa6b2'
down_revision = '2646af2341c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
