"""adding uploaded_picture column

Revision ID: ddb5ba6d4feb
Revises: 21cea4fab8bf
Create Date: 2023-07-13 09:31:02.938733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb5ba6d4feb'
down_revision = '21cea4fab8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_picture', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('uploaded_picture')

    # ### end Alembic commands ###
